### ISSUE TITLE
[Object-refactoring] Add limit to batch size

### ISSUE THREAD

**Issue by eemhu** [teragrep/pth_06#15]
Need to implement a limit object, which checks the current weight of the batch and limits the batch to a certain weight given in the configuration.

The current situation is that the latestOffset call increments the offset to the next available one, and using that offset, planInputPartition plans the batch. This needs to be connected in a way that latestOffset updates to the offset that is reached on max weight and Spark then knows to call planInputPartitions from that offset onwards.

**Comment by eemhu** [comment]
Implemented BatchSizeLimit object which limits the batch size based on a WeightedOffset. The weight is estimated based on fileSize, compressionRatio and processingSpeed. It also has an object count limit if the weights are too small to be significant.

**Comment by kortemik** [comment]
currently it has quite slow progress

```
%dpl

index=f17 timeformat=%s earliest=0
```
Full table input rows read from archive: 122342400 during batchId: 1, with avg EPS: 113006.58684128123

122342400/113006.58684128123
1082.61300000000003314859

seconds per batch update

**Comment by eemhu** [comment]
fixed f17_mini issue: Switched 'logtime' field from ULong to Long. Negative epochs caused overflow and looped back to MAX long value.
Added configuration options for customizing batch size via fileCompressionRatio and processingSpeed.
