### ISSUE TITLE
[Object-refactoring] Earliest value is not exact

### ISSUE THREAD

**Issue by eemhu** [teragrep/pth_06#16]
On old Spark 2.x version, this results in `1,000,100` (full dataset). In Spark 3.x version, it misses some initial events as the final count is `997,624`.
```
index=crud earliest=2021-01-01T00:00:00.000+02:00 | stats count
```

To get all data, earliest must be moved one day back. (`2020-12-31` vs. `2021-01-01`). This results in the expected
`1,000,100` final count.
```
index=crud earliest=2020-12-31T00:00:00.000+02:00 | stats count
```

**Comment by kortemik** [comment]
could this be because of some changes between spark2.4 and spark3? timezones perhaps?

**Comment by eemhu** [comment]
SliceTable was always empty on earliest value. Added pullToSliceTable call on first day to fix.
