### ISSUE TITLE
add option to return files that do not have bloomfilter

### ISSUE THREAD

**Issue by kortemik** [teragrep/pth_06#24]
**Description**
creation of bloomfilters requires that the files do not have bloomfilter present, otherwise they are created but rejected because that would insert a duplicate key 
 
**Use case or motivation behind the feature request**
simplifies the bloomfilter creation process
 
**Related issues**

 
**Additional context**

**Comment by elliVM** [comment]
Added condition to ConditionWalker to get journaldb.logfiles without FK reference from bloomdb.bloomfilter

**Comment by elliVM** [comment]
In testing ConditionWalker condition
 ```queryCondition = BLOOMDB.BLOOMFILTER.FILTER.isNull();``` 
does not work even when bloom is enabled and left joined with 
``` selectOnConditionStep = selectOnConditionStep.leftJoin(
                                Bloomdb.BLOOMDB.BLOOMFILTER).on(
                                JOURNALDB.LOGFILE.ID.eq(Bloomdb.BLOOMDB.BLOOMFILTER.PARTITION_ID)
                );
```

Same condition is used later in bloomsearch in getting files without filters

**Comment by elliVM** [comment]
Added pth_06.bloom.withoutFilter interpreter setting config to enable search for files without filters, added needed changes to pth_07 and pth_10

**Comment by elliVM** [comment]
Tested in QA and PR open

**Comment by kortemik** [comment]
pr ok to merge
