### ISSUE TITLE
Running query without bloom enabled results in error

### ISSUE THREAD

**Issue by eemhu** [teragrep/pth_06#72]
**Describe the bug**

Running 
```
index=example earliest=-10y@y
results in
Table 'bloomdb.filter_expected_100000_fpp_001' doesn't exist
```

 
**Expected behavior**

should work without errors as bloom is not enabled
 
**How to reproduce**

run command above
 
**Screenshots**

 
**Software version**

3.1.2
 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by elliVM** [comment]
Bug in PTH-10 that defaulted bloom to be enabled, patched in version 5.1.1
