### ISSUE TITLE
add hashcode to the objects where equals is present

### ISSUE THREAD

**Issue by kortemik** [teragrep/pth_06#98]
**Description**
add hashcode to the objects where equals is present

see more at https://www.baeldung.com/java-equals-hashcode-contracts

**Comment by StrongestNumber9** [comment]
Example project that can be found [here](https://github.com/teragrep/mvn_01/tree/main/equalsverifier)

**Comment by elliVM** [comment]
Fixed in https://github.com/teragrep/pth_06/pull/141
